# 连接池配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql:///mybatis-plus-example
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 控制台输出SQL语句
  type-aliases-package: org.example.pojo
  global-config:
    db-config:
      id-type: auto  # 全局设置为auto
      logic-delete-field: deleted  # 逻辑删除属性名
